name: "🐝 Bug Report"
description: "In case something is broken or doesn't work as expected."
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        # Please read here
        **Warning**: you are opening a bug report for the live ISO, it means you have problems installing or booting the installation device. If you want to report a bug for Vanilla OS, please use the [desktop](https://github.com/Vanilla-OS/desktop-image)/[vm](https://github.com/Vanilla-OS/vm-image)/[nvidia](https://github.com/Vanilla-OS/nvidia-image) repo.
        
        Thanks for taking the time to help us
        --------
        Don't worry, we eat bugs for breakfast.
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: |
        Tell us, what's the problem? But please keep it brief and on point.
        Feel free to add screenshots or other necessary attachments.
      placeholder: |
        Sometimes I get booted into the C partition I never knew existed.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        What steps would we have to take to reproduce the issue?
      placeholder: |
          - Flashed the ISO on my USB device
          - Tried to boot it
          - Nothing happen
    validations:
      required: true
  - type: dropdown
    id: os-version
    attributes:
      label: On what version of Vanilla OS this happens?
      options:
        - "Vanilla OS 2 Orchid"
        - "Unreleased"
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: |
        If you feel like it, share some thoughts or additional context.
      placeholder: |
        Maybe this is a leftover from my previous OS? IIRC, it used to be installed in the C partition.
